version: 2.1
orbs:
  samvera: samvera/circleci-orb@1
  browser-tools: circleci/browser-tools@1.3
  ruby: circleci/ruby@2
  node: circleci/node@5

jobs:
  bundle:
    parameters:
      ruby_version:
        type: string
        default: 2.7.7
      bundler_version:
        type: string
        default: 2.4.8
      rails_version:
        type: string
        default: 6.1.7.2
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    steps:
      - samvera/cached_checkout

      - run:
          name: Check for a branch named 'master'
          command: |
            git fetch --all --quiet --prune --prune-tags
            if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
            fi
            [[ -z "$(git branch --all --list master */master)" ]]

      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>

      # Run rubocop in parallel with caching
      # This should get added to the orb once proven here

      - restore_cache:
          name: Restore rubocop cache
          keys:
            - v1-rubocop-ruby<< parameters.ruby_version >>-bundle{{ checksum "Gemfile.lock" }}
            - v1-rubocop-ruby<< parameters.ruby_version >>
            - v1

      - run:
          name: Run rubocop in parallel
          command: bundle exec rubocop --parallel

      - save_cache:
          name: Save rubocop cache
          key: v1-rubocop-ruby<< parameters.ruby_version >>-bundle{{ checksum "Gemfile.lock" }}
          paths:
            - ~/.cache/rubocop_cache

      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  build:
    parameters:
      ruby_version:
        type: string
        default: 2.7.7
      bundler_version:
        type: string
        default: 2.4.8
      rails_version:
        type: string
        default: 6.1.7.2
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis_postgres'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium
    environment:
      RAILS_VERSION: << parameters.rails_version >>
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      ENGINE_CART_RAILS_OPTIONS: --database=postgresql --skip-git --skip-bundle --skip-listen --skip-spring --skip-keeps --skip-test --skip-bootsnap --skip-javascript
      DATABASE_URL: postgresql://postgres@127.0.0.1/circle_test # Hard-coded with data from CircleCI orb, related to https://github.com/samvera-labs/samvera-circleci-orb/issues/42
    steps:
      - attach_workspace:
          at: ~/
      - samvera/engine_cart_generate:
          cache_key: v1-internal-test-app-{{ checksum "hyrax.gemspec" }}-{{ checksum ".regen" }}-{{ checksum ".circleci/config.yml" }}-<< parameters.rails_version >>-<< parameters.ruby_version >>
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      - run:
          name: Generate .internal_test_app/Gemfile.lock
          command: bundle lock
          working_directory: .internal_test_app
      - ruby/install-deps:
          app-dir: .internal_test_app
      - node/install-packages:
          pkg-manager: yarn
          app-dir: .internal_test_app
      - persist_to_workspace:
          root: ~/
          paths:
          - project/*
          - project/**/*

  test:
    parameters:
      ruby_version:
        type: string
        default: 2.7.7
      bundler_version:
        type: string
        default: 2.4.8
      hyrax_valkyrie:
        type: string
        default: "false"
     
    executor:
      name: 'samvera/ruby_fcrepo_solr_redis_postgres'
      ruby_version: << parameters.ruby_version >>
    resource_class: medium+
    parallelism: 10
    environment:
      HYRAX_VALKYRIE: << parameters.hyrax_valkyrie >>
      VALKYRIE_SOLR_PORT: 8985
      DATABASE_URL: postgresql://postgres@127.0.0.1/circle_test # Hard-coded with data from CircleCI orb, related to https://github.com/samvera-labs/samvera-circleci-orb/issues/42
      KARMA_BROWSER: ChromeHeadlessCustom
      RAILS_ROOT: .internal_test_app
      SPEC_OPTS: "" # Clear output conflicts between samvera orb executor and ruby orb rspec command
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install imagemagick librsvg2-bin lsof
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome install
          command: |
            google-chrome --version
            chromedriver --version
      - restore_cache:
          keys:
            - engine-node-v1-{{ checksum "package.json" }}
      # Call yarn directly for hyrax engine; node orb demands a lockfile to use caching
      - run:
          name: Yarn Install (engine)
          command: yarn install
      - save_cache:
          key: engine-node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf
          core_name: hyrax-valkyrie-test
      # Rerun bundler in case this is a different ruby version than bundle and build steps
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      # Ensure gems needed by the test app are installed
      - ruby/install-deps:
          app-dir: .internal_test_app
      - node/install-packages:
          pkg-manager: yarn
          app-dir: .internal_test_app
      - run:
          command: bundle exec rake db:migrate
          working_directory: .internal_test_app
      - ruby/rspec-test
      - store_artifacts:
          path: Gemfile.lock
          destination: engine-gemfile-lock
      - store_artifacts:
          path: .internal_test_app/Gemfile.lock
          destination: webapp-gemfile-lock

  test-nofcrepo:
    parameters:
      postgres_version:
        type: string
        default: '9.6'
      redis_version:
        type: string
        default: '6.2'
      ruby_type:
        type: string
        default: 'ruby'
      ruby_version:
        type: string
        default: '2.5.5'
      solr_port:
        type: string
        default: '8985'
      solr_version:
        type: string
        default: 'slim'
      bundler_version:
        type: string
        default: 2.4.8
      skip_wings:
        type: string
        default: "false"

    docker:
      - image: cimg/<< parameters.ruby_type >>:<< parameters.ruby_version >>-browsers
      - image: zookeeper:3.4
      - image: solr:<< parameters.solr_version >>
        environment:
          VERBOSE: yes
          SECURITY_JSON: '{"authentication":{"blockUnknown": false, "class":"solr.BasicAuthPlugin", "credentials":{"solr":"IV0EHq1OnNrj6gvRCwvFwTrZ1+z1oBbnQdiVC3otuq0= Ndd7LKvVBAaZIF0QAVi1ekCfAJXr1GGfLtRUXhgrF8c="}, "realm":"My Solr users", "forwardCredentials": false}, "authorization":{ "class":"solr.RuleBasedAuthorizationPlugin", "permissions":[{"name":"security-edit", "role":"admin"}], "user-role":{"solr":"admin"}}}'
        command: sh -c "server/scripts/cloud-scripts/zkcli.sh -zkhost localhost:2181 -cmd put /security.json \"${SECURITY_JSON}\" && solr-fg -cloud -noprompt  -p << parameters.solr_port >> -z localhost:2181"
      - image: redis:<< parameters.redis_version >>
      - image: cimg/postgres:<< parameters.postgres_version >>     
    parallelism: 10
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
      RAILS_ENV: test
      RACK_ENV: test
      POSTGRES_DB: circle_test
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: postgres
      HYRAX_SKIP_WINGS: << parameters.skip_wings >>
      VALKYRIE_SOLR_PORT: 8985
      DATABASE_URL: postgresql://postgres@127.0.0.1/circle_test # Hard-coded with data from CircleCI orb, related to https://github.com/samvera-labs/samvera-circleci-orb/issues/42
      KARMA_BROWSER: ChromeHeadlessCustom
      RAILS_ROOT: .internal_test_app
      SOLR_URL: http://127.0.0.1:8985/solr/hyrax-valkyrie-test # Force to use valkyrie solr core
      SPEC_OPTS: "" # Clear output conflicts between samvera orb executor and ruby orb rspec command
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install imagemagick librsvg2-bin lsof
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Chrome install
          command: |
            google-chrome --version
            chromedriver --version
      - restore_cache:
          keys:
            - engine-node-v1-{{ checksum "package.json" }}
      # Call yarn directly for hyrax engine; node orb demands a lockfile to use caching
      - run:
          name: Yarn Install (engine)
          command: yarn install
      - save_cache:
          key: engine-node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf
      - samvera/install_solr_core:
          solr_config_path: .internal_test_app/solr/conf
          core_name: hyrax-valkyrie-test
      # Rerun bundler in case this is a different ruby version than bundle and build steps
      - samvera/bundle:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
      # Ensure gems needed by the test app are installed
      - ruby/install-deps:
          app-dir: .internal_test_app
      - node/install-packages:
          pkg-manager: yarn
          app-dir: .internal_test_app
      - run:
          command: bundle exec rake db:migrate
          working_directory: .internal_test_app
      - ruby/rspec-test:
          include: "spec/abilities/**/*_spec.rb,spec/actors/**/*_spec.rb,spec/authorities/**/*_spec.rb,spec/channels/**/*_spec.rb,spec/config/**/*_spec.rb,spec/controllers/**/*_spec.rb,spec/factory_tests/**/*_spec.rb,spec/features/**/*_spec.rb,spec/forms/**/*_spec.rb,spec/helpers/**/*_spec.rb,spec/hyrax/**/*_spec.rb,spec/indexers/**/*_spec.rb,spec/inputs/**/*_spec.rb,spec/javascripts/**/*_spec.rb,spec/jobs/**/*_spec.rb,spec/lib/**/*_spec.rb,spec/matcher_tests/**/*_spec.rb,spec/models/**/*_spec.rb,spec/presenters/**/*_spec.rb,spec/renderers/**/*_spec.rb,spec/requests/**/*_spec.rb,spec/routing/**/*_spec.rb,spec/search_builders/**/*_spec.rb,spec/services/**/*_spec.rb,spec/strategies/**/*_spec.rb,spec/tasks/**/*_spec.rb,spec/utils/**/*_spec.rb,spec/validators/**/*_spec.rb,spec/valkyrie/**/*_spec.rb,spec/views/**/*_spec.rb"
      - store_artifacts:
          path: Gemfile.lock
          destination: engine-gemfile-lock
      - store_artifacts:
          path: .internal_test_app/Gemfile.lock
          destination: webapp-gemfile-lock

workflows:
  version: 2
  ruby3-2:
    jobs:
      - bundle:
          ruby_version: "3.2.2"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
      - build:
          ruby_version: "3.2.2"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
          requires:
            - bundle
      - test:
          name: "ruby3-2"
          ruby_version: "3.2.2"
          bundler_version: "2.4.8"
          requires:
            - build
      - test:
          name: "ruby3-2-valkyrie"
          ruby_version: "3.2.2"
          bundler_version: "2.4.8"
          hyrax_valkyrie: "true"
          requires:
            - build
      - test-nofcrepo:
          name: "ruby3-2-valkyrie"
          ruby_version: "3.2.2"
          bundler_version: "2.4.8"
          skip_wings: "true"
          requires:
            - build
  ruby3-1:
    jobs:
      - bundle:
          ruby_version: "3.1.4"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
      - build:
          ruby_version: "3.1.4"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
          requires:
            - bundle
      - test:
          name: "ruby3-1"
          ruby_version: "3.1.4"
          bundler_version: "2.4.8"
          requires:
            - build
  ruby3-0:
    jobs:
      - bundle:
          ruby_version: "3.0.6"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
      - build:
          ruby_version: "3.0.6"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
          requires:
            - bundle
      - test:
          name: "ruby3-0"
          ruby_version: "3.0.6"
          bundler_version: "2.4.8"
          requires:
            - build
  ruby2-7:
    jobs:
      - bundle:
          ruby_version: "2.7.7"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
      - build:
          ruby_version: "2.7.7"
          rails_version: "6.1.7.2"
          bundler_version: "2.4.8"
          requires:
            - bundle
      - test:
          name: "ruby2-7"
          ruby_version: "2.7.7"
          bundler_version: "2.4.8"
          requires:
            - build
      - test:
          name: "ruby2-7-valkyrie"
          ruby_version: "2.7.7"
          bundler_version: "2.4.8"
          hyrax_valkyrie: "true"
          requires:
            - build
